# This rule is not used by the project managed-postgres-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the managed-postgres-operator.hoppscale.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: managed-postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresschema-editor-role
rules:
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresschemas/status
  verbs:
  - get
